# Deep Learning with PyTorch

## Introduction

### Tensors

In [1]:
import numpy as np
np.random.seed(0)
import torch
torch.manual_seed(0)

a = np.array([
    [2, 3, 5],
    [1, 2, 9]
])
print(a)

a = torch.tensor([
    [2, 3, 5],
    [1, 2, 9]
])
if torch.cuda.is_available():
    a = a.cuda()
print(a)

a = np.random.randn(3, 5)
print(a, "\nshape:", a.shape)

a = torch.randn(size=(3, 5))
if torch.cuda.is_available():
    a = a.cuda()
print(a, "\nshape:", a.shape)

[[2 3 5]
 [1 2 9]]
tensor([[2, 3, 5],
        [1, 2, 9]], device='cuda:0')
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]] 
shape: (3, 5)
tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845],
        [-1.3986,  0.4033,  0.8380, -0.7193, -0.4033],
        [-0.5966,  0.1820, -0.8567,  1.1006, -1.0712]], device='cuda:0') 
shape: torch.Size([3, 5])


In [13]:
import numpy as np
np.random.seed(0)
import torch
torch.manual_seed(0)

a = np.random.rand(2, 2)
b = np.random.rand(2, 2)
# Dot product
print(np.dot(a=a, b=b))
# Element-wise multiplication
print(np.multiply(a, b))

a = torch.rand(size=(2, 2))
b = torch.rand(size=(2, 2))

if torch.cuda.is_available():
    a = a.cuda()
    b = b.cuda()

# Dot product
print(torch.matmul(input=a, other=b))
# Element-wise multiplication
print(a * b)

[[0.5454652  0.99226198]
 [0.49379751 0.87523343]]
[[0.23250747 0.4619366 ]
 [0.26376154 0.48591211]]
tensor([[0.5291, 1.0033],
        [0.0919, 0.1745]], device='cuda:0')
tensor([[0.1526, 0.4871],
        [0.0434, 0.1184]], device='cuda:0')


In [8]:
import numpy as np
np.random.seed(0)
import torch
torch.manual_seed(0)

a = np.zeros(shape=(2, 2))
print(a)

a = torch.zeros(size=(2, 2))
if torch.cuda.is_available():
    a = a.cuda()
print(a)

a = np.ones(shape=(2, 2))
print(a)

a = torch.ones(size=(2, 2))
if torch.cuda.is_available():
    a = a.cuda()
print(a)

a = np.identity(n=2)
print(a)

a = torch.eye(n=2)
if torch.cuda.is_available():
    a = a.cuda()
print(a)

[[0. 0.]
 [0. 0.]]
tensor([[0., 0.],
        [0., 0.]], device='cuda:0')
[[1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
[[1. 0.]
 [0. 1.]]
tensor([[1., 0.],
        [0., 1.]], device='cuda:0')


In [10]:
import numpy as np
np.random.seed(0)
import torch
torch.manual_seed(0)

a = np.random.rand(2, 2)
a = torch.from_numpy(a)

if torch.cuda.is_available():
    a = a.cuda()

a = a.cpu()
print(a.numpy())

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]


In [11]:
# Import torch
import torch
torch.manual_seed(0)

# Create random tensor of size 3 by 3
a = torch.rand(size=(3, 3))

if torch.cuda.is_available():
    a = a.cuda()

# Calculate the shape of the tensor
a_shape = a.shape

# Print the values of the tensor and its shape
print(a)
print(a_shape)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556]], device='cuda:0')
torch.Size([3, 3])


In [14]:
import torch
torch.manual_seed(0)

# Create a matrix of ones with shape 3 by 3
a = torch.ones(size=(3, 3))
# Create an identity matrix with shape 3 by 3
b = torch.eye(n=3)

if torch.cuda.is_available():
    a = a.cuda()
    b = b.cuda()

# Matrix multiplication of a with b
c = torch.matmul(input=a, other=b)
print(c)

# Element-wise multiplication of a with b
c = a * b
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0')


### Forward propagation

In [15]:
import torch
torch.manual_seed(0)

a = torch.Tensor([2])
b = torch.Tensor([-4])
c = torch.Tensor([-2])
d = torch.Tensor([2])

if torch.cuda.is_available():
    a = a.cuda()
    b = b.cuda()
    c = c.cuda()
    d = d.cuda()

e = a + b
f = c * d
g = e * f
print(e, f, g)

tensor([-2.], device='cuda:0') tensor([-4.], device='cuda:0') tensor([8.], device='cuda:0')


In [16]:
import torch
torch.manual_seed(0)

# Initialize tensors x, y and z
x = torch.rand(size=(1000, 1000))
y = torch.rand(size=(1000, 1000))
z = torch.rand(size=(1000, 1000))

if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = z.cuda()

# Multiply x with y
q = torch.matmul(input=x, other=y)
# Multiply element-wise z with q
f = z * q
mean_f = torch.mean(input=f)
print(mean_f)

tensor(125.1406, device='cuda:0')


### Backpropagation

In [1]:
import torch
torch.manual_seed(0)

# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., requires_grad=True)
y = torch.tensor(-3., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

# Set q to sum of x and y
q = x + y
# Set f to product of q with z
f = q * z
# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of z is:", z.grad)
print("Gradient of y is:", y.grad)
print("Gradient of x is:", x.grad)

Gradient of z is: tensor(1.)
Gradient of y is: tensor(5.)
Gradient of x is: tensor(5.)


In [ ]:
import torch
torch.manual_seed(0)

# Initialize tensors x, y and z
x = torch.rand(size=(1000, 1000))
y = torch.rand(size=(1000, 1000))
z = torch.rand(size=(1000, 1000))

if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = z.cuda()

# Multiply tensors x and y
q = torch.matmul(input=x, other=y)
# Element-wise multiply tensors z with q
f = z * q
mean_f = torch.mean(input=f)
# Calculate the gradients
mean_f.backward()

### Neural networks

In [1]:
import torch
torch.manual_seed(0)

input_layer = torch.rand(10)
w1 = torch.rand(size=(10, 20))
w2 = torch.rand(size=(20, 20))
w3 = torch.rand(size=(20, 4))

if torch.cuda.is_available():
    input_layer = input_layer.cuda()
    w1 = w1.cuda()
    w2 = w2.cuda()
    w3 = w3.cuda()

h1 = torch.matmul(input=input_layer, other=w1)
h2 = torch.matmul(input=h1, other=w2)
output_layer = torch.matmul(input=h2, other=w3)
print(output_layer)

tensor([243.7668, 219.5830, 211.5230, 254.8253], device='cuda:0')


In [3]:
import torch
torch.manual_seed(0)

input_layer = torch.rand(784)
# Initialize the weights of the neural network
weight_1 = torch.rand(size=(784, 200))
weight_2 = torch.rand(size=(200, 10))

if torch.cuda.is_available():
    input_layer = input_layer.cuda()
    weight_1 = weight_1.cuda()
    weight_2 = weight_2.cuda()

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input=input_layer, other=weight_1)
# Multiply hidden_1 with weight_2
output_layer = torch.matmul(input=hidden_1, other=weight_2)
print(output_layer)

tensor([21105.2676, 19629.4141, 18506.6523, 19196.1504, 19759.8438, 19620.8242,
        19557.7090, 21682.9746, 19894.4688, 19432.3047], device='cuda:0')


In [2]:
import torch
torch.manual_seed(0)

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(in_features=10, out_features=20)
        self.fc2 = torch.nn.Linear(in_features=20, out_features=20)
        self.output = torch.nn.Linear(in_features=20, out_features=4)

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.output(x)
        return x

input_layer = torch.rand(10)
net = Net()

if torch.cuda.is_available():
    input_layer = input_layer.cuda()
    net = net.cuda()

result = net(input_layer)
print(result)

tensor([-0.0571,  0.1801, -0.0272, -0.0133], device='cuda:0',
       grad_fn=<ViewBackward0>)


In [4]:
import torch
torch.manual_seed(0)

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(in_features=784, out_features=200)
        self.fc2 = torch.nn.Linear(in_features=200, out_features=10)

    def forward(self, x):
        # use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x

input_layer = torch.rand(784)
net = Net()

if torch.cuda.is_available():
    input_layer = input_layer.cuda()
    net = net.cuda()

result = net(input_layer)
print(result)

tensor([-0.1113, -0.0151,  0.1005,  0.2801,  0.2317, -0.1189, -0.3775,  0.0440,
         0.3325, -0.1394], device='cuda:0', grad_fn=<ViewBackward0>)


## Artificial Neural Networks

### Activation functions