# Introduction to Deep Learning with PyTorch

## Introduction to PyTorch

### Tensors

In [1]:
import numpy as np
import torch

array = [[1, 2, 3], [4, 5, 6]]    
tensor = torch.tensor(array)
if torch.cuda.is_available():
    tensor = tensor.cuda()
    
print("Tensor shape:", tensor.shape)
print("Tensor dtype:", tensor.dtype)
print("Tensor device:", tensor.device)

np_array = np.array(array)
np_tensor = torch.from_numpy(np_array)
if torch.cuda.is_available():
    np_tensor = np_tensor.cuda()

print("Input tensor:", np_tensor)
print("Input tensor device:", np_tensor.device)

Tensor shape: torch.Size([2, 3])
Tensor dtype: torch.int64
Tensor device: cuda:0
Input tensor: tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')
Input tensor device: cuda:0


In [2]:
import torch

a = torch.tensor([[1, 1], [2, 2]])
b = torch.tensor([[2, 2], [3, 3]])
c = torch.tensor([[2, 2, 4], [3, 3, 5]])

if torch.cuda.is_available():
    a = a.cuda()
    b = b.cuda()
    c = c.cuda()

print(a + b)
print(a * b)
print(a + c)

tensor([[3, 3],
        [5, 5]], device='cuda:0')
tensor([[2, 2],
        [6, 6]], device='cuda:0')


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [3]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)
if torch.cuda.is_available():
    tensor_a = tensor_a.cuda()
print(tensor_a)
# Display the tensor device
print("Device:", tensor_a.device)
# Display the tensor data type
print("Dtype:", tensor_a.dtype)

tensor([1, 2, 3, 4], device='cuda:0')
Device: cuda:0
Dtype: torch.int64


In [4]:
import numpy as np
import torch

# Create two tensors from the arrays
array_a = np.array([
    [1, 1, 1],
    [2, 3, 4],
    [4, 5, 6]
])
array_b = np.array([
    [7, 5, 4],
    [2, 2, 8],
    [6, 3, 8]
])
tensor_a = torch.from_numpy(array_a)
tensor_b = torch.from_numpy(array_b)
if torch.cuda.is_available():
    tensor_a = tensor_a.cuda()
    tensor_b = tensor_b.cuda()

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c with tensor_d
tensor_e = tensor_c + tensor_d
print(tensor_e)

tensor([[ 1,  1,  1],
        [ 4,  7, 28],
        [22, 17, 46]], device='cuda:0')


### Neural Network

In [5]:
import torch

# Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

# Define first linear layer
linear_layer = torch.nn.Linear(in_features=3, out_features=2)
print("Weight:", linear_layer.weight)
print("Bias:", linear_layer.bias)

if torch.cuda.is_available():
    input_tensor = input_tensor.cuda()
    linear_layer = linear_layer.cuda()

# Pass input through linear layer
output = linear_layer(input_tensor)
print("Output:", output)

Weight: Parameter containing:
tensor([[ 0.3566, -0.4520, -0.3941],
        [ 0.2633,  0.2730,  0.5414]], requires_grad=True)
Bias: Parameter containing:
tensor([0.0508, 0.0935], requires_grad=True)
Output: tensor([[0.0619, 0.1814]], device='cuda:0', grad_fn=<AddmmBackward0>)


In [6]:
import torch

input_tensor = torch.tensor([
    [-0.0014, 0.4038, 1.0305, 0.7521, 0.7489, -0.3968, 0.0113, -1.3844, 0.8705, -0.9743]
])

# Create network with three linear layers
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=10, out_features=18),
    torch.nn.Linear(in_features=18, out_features=20),
    torch.nn.Linear(in_features=20, out_features=5)
)

if torch.cuda.is_available():
    input_tensor = input_tensor.cuda()
    model = model.cuda()

# Pass input_tensor to model to obtain output
output_tensor = model(input_tensor)
print(output_tensor)

tensor([[0.3557, 0.0388, 0.1539, 0.3063, 0.0142]], device='cuda:0',
       grad_fn=<AddmmBackward0>)


In [7]:
import torch

input_tensor = torch.tensor([[2, 3, 6, 7, 9, 3, 2, 1]], dtype=torch.float32)

# Implement a small neural network with exactly two linear layer
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=8, out_features=4),
    torch.nn.Linear(in_features=4, out_features=1)
)

if torch.cuda.is_available():
    input_tensor = input_tensor.cuda()
    model = model.cuda()

output = model(input_tensor)
print(output)

tensor([[0.2472]], device='cuda:0', grad_fn=<AddmmBackward0>)


### Activation Functions

In [8]:
import torch

input = torch.tensor([[6.0]])
sigmoid = torch.nn.Sigmoid()

if torch.cuda.is_available():
    input = input.cuda()
    sigmoid = sigmoid.cuda()

output = sigmoid(input)
print("Output sigmoid:", output)

# Create an input tensor
input = torch.tensor([[4.3, 6.1, 2.3]])
# Apply softmax along the last dimension
probabilities = torch.nn.Softmax(dim=-1)

if torch.cuda.is_available():
    input = input.cuda()
    probabilities = probabilities.cuda()

output = probabilities(input)
print("Output softmax:", output)

Output sigmoid: tensor([[0.9975]], device='cuda:0')
Output softmax: tensor([[0.1392, 0.8420, 0.0188]], device='cuda:0')


In [9]:
import torch

input = torch.rand(size=(6,))

model = torch.nn.Sequential(
    torch.nn.Linear(in_features=6, out_features=4), # First linear layer
    torch.nn.Linear(in_features=4, out_features=1), # Second linear layer
    torch.nn.Sigmoid() # Sigmoid activation function
)

if torch.cuda.is_available():
    input = input.cuda()
    model = model.cuda()

output = model(input)
print("Output sigmoid:", output)

Output sigmoid: tensor([0.4616], device='cuda:0', grad_fn=<SigmoidBackward0>)


In [10]:
import torch

score = torch.tensor([[0.8]])
# Create a sigmoid function and apply it on the score tensor
sigmoid = torch.nn.Sigmoid()

if torch.cuda.is_available():
    score = score.cuda()
    sigmoid = sigmoid.cuda()

probability = sigmoid(score)
print("Probability:", probability)

Probability: tensor([[0.6900]], device='cuda:0')


## Training Neural Network

### Forward pass

In [11]:
import torch

# Create input data of shape 5x6
input = torch.tensor([
    [-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
    [-0.9155, -0.0475, -1.3645, 0.6336, -0.19520, -0.3398],
    [0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633],
    [-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
    [-0.7413, 1.7920, -0.0883, -0.6685, 0.4745, -0.4245]
])

# Create binary classification model
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=6, out_features=4), # First linear layer
    torch.nn.Linear(in_features=4, out_features=1), # Second linear layer
    torch.nn.Sigmoid() # Sigmoid activation function
)

if torch.cuda.is_available():
    input = input.cuda()
    model = model.cuda()

# Pass input data through model
output = model(input)
print("Output shape:", output.shape)
print("Output:", output)

Output shape: torch.Size([5, 1])
Output: tensor([[0.5250],
        [0.6473],
        [0.6317],
        [0.6099],
        [0.5529]], device='cuda:0', grad_fn=<SigmoidBackward0>)


In [12]:
import torch

# Create input data of shape 5x6
input = torch.tensor([
    [-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
    [-0.9155, -0.0475, -1.3645, 0.6336, -0.19520, -0.3398],
    [0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633],
    [-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
    [-0.7413, 1.7920, -0.0883, -0.6685, 0.4745, -0.4245]
])

# Specify model has three classes
n_classes = 3

# Create multiclass classification model
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=6, out_features=4), # First linear layer
    torch.nn.Linear(in_features=4, out_features=n_classes), # Second linear layer
    torch.nn.Softmax(dim=-1) # Softmax activation
)

if torch.cuda.is_available():
    input = input.cuda()
    model = model.cuda()

# Pass input data through model
output = model(input)
print("Output shape:", output.shape)
print("Output:", output)

Output shape: torch.Size([5, 3])
Output: tensor([[0.1933, 0.3578, 0.4489],
        [0.4236, 0.3440, 0.2324],
        [0.2135, 0.4184, 0.3681],
        [0.5118, 0.2789, 0.2093],
        [0.2511, 0.3395, 0.4094]], device='cuda:0', grad_fn=<SoftmaxBackward0>)


In [13]:
import torch

# Create input data of shape 5x6
input = torch.tensor([
    [-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
    [-0.9155, -0.0475, -1.3645, 0.6336, -0.19520, -0.3398],
    [0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633],
    [-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
    [-0.7413, 1.7920, -0.0883, -0.6685, 0.4745, -0.4245]
])

# Create regression model
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=6, out_features=4), # First linear layer
    torch.nn.Linear(in_features=4, out_features=1) # Second linear layer
)

if torch.cuda.is_available():
    input = input.cuda()
    model = model.cuda()

# Pass input data through model
output = model(input)
# Return output
print("Output shape:", output.shape)
print("Output:", output)

Output shape: torch.Size([5, 1])
Output: tensor([[0.6174],
        [0.0160],
        [0.5300],
        [0.0303],
        [0.4809]], device='cuda:0', grad_fn=<AddmmBackward0>)


In [14]:
import torch

input = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=8, out_features=1),
    torch.nn.Sigmoid()
)

if torch.cuda.is_available():
    input = input.cuda()
    model = model.cuda()

output = model(input)
print("Output shape:", output.shape)
print("Output:", output)

Output shape: torch.Size([1, 1])
Output: tensor([[0.6650]], device='cuda:0', grad_fn=<SigmoidBackward0>)


In [ ]:
import torch

input = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=11, out_features=20),
    torch.nn.Linear(in_features=20, out_features=12),
)