# Introduction to Deep Learning with PyTorch

## Introduction to PyTorch

### Tensors

In [17]:
import numpy as np
import torch

array = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(array)
print("Tensor shape:", tensor.shape)
print("Tensor dtype:", tensor.dtype)
print("Tensor device:", tensor.device)

np_array = np.array(array)
np_tensor = torch.from_numpy(np_array)
print(np_tensor)

Tensor shape: torch.Size([2, 3])
Tensor dtype: torch.int64
Tensor device: cpu
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
import torch

a = torch.tensor([[1, 1], [2, 2]])
b = torch.tensor([[2, 2], [3, 3]])
c = torch.tensor([[2, 2, 4], [3, 3, 5]])

print(a + b)
print(a * b)
print(a + c)

tensor([[3, 3],
        [5, 5]])
tensor([[2, 2],
        [6, 6]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [16]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)
print(tensor_a)
# Display the tensor device
print("Device:", tensor_a.device)
# Display the tensor data type
print("Dtype:", tensor_a.dtype)

tensor([1, 2, 3, 4])
Device: cpu
Dtype: torch.int64


In [10]:
import numpy as np
import torch

array_a = np.array([
    [1, 1, 1],
    [2, 3, 4],
    [4, 5, 6]
])

array_b = np.array([
    [7, 5, 4],
    [2, 2, 8],
    [6, 3, 8]
])

# Create two tensors from the arrays
tensor_a = torch.from_numpy(array_a)
tensor_b = torch.from_numpy(array_b)

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c with tensor_d
tensor_e = tensor_c + tensor_d
print(tensor_e)

tensor([[ 1,  1,  1],
        [ 4,  7, 28],
        [22, 17, 46]])


### Neural Network

In [15]:
import torch

# Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

# Define first linear layer
linear_layer = torch.nn.Linear(in_features=3, out_features=2)
print("Weight:", linear_layer.weight)
print("Bias:", linear_layer.bias)

# Pass input through linear layer
output = linear_layer(input_tensor)
print("Output:", output)

Weight: Parameter containing:
tensor([[ 0.2944, -0.4310, -0.4302],
        [-0.1530,  0.4387,  0.4528]], requires_grad=True)
Bias: Parameter containing:
tensor([-0.2241, -0.3048], requires_grad=True)
Output: tensor([[-0.2166, -0.2651]], grad_fn=<AddmmBackward0>)


In [18]:
import torch

input_tensor = torch.tensor([
    [-0.0014, 0.4038, 1.0305, 0.7521, 0.7489, -0.3968, 0.0113, -1.3844, 0.8705, -0.9743]
])

# Create network with three linear layers
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=10, out_features=18),
    torch.nn.Linear(in_features=18, out_features=20),
    torch.nn.Linear(in_features=20, out_features=5)
)

# Pass input_tensor to model to obtain output
output_tensor = model(input_tensor)
print(output_tensor)

tensor([[ 0.3791, -0.1998,  0.0790,  0.3923,  0.1201]],
       grad_fn=<AddmmBackward0>)


In [5]:
import torch

input_tensor = torch.tensor([[2, 3, 6, 7, 9, 3, 2, 1]], dtype=torch.float32)

# Implement a small neural network with exactly two linear layer
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=8, out_features=4),
    torch.nn.Linear(in_features=4, out_features=1)
)

output = model(input_tensor)
print(output)

tensor([[-0.1347]], grad_fn=<AddmmBackward0>)


### Activation Functions

In [6]:
import torch

input = torch.tensor([[6.0]])
sigmoid = torch.nn.Sigmoid()
output = sigmoid(input)
print("Output sigmoid:", output)

# Create an input tensor
input = torch.tensor([[4.3, 6.1, 2.3]])
# Apply softmax along the last dimension
probabilities = torch.nn.Softmax(dim=-1)
output = probabilities(input)

print("Output softmax:", output)

Output sigmoid: tensor([[0.9975]])
Output softmax: tensor([[0.1392, 0.8420, 0.0188]])


In [8]:
import torch

input = torch.rand(6)
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=6, out_features=4), # First linear layer
    torch.nn.Linear(in_features=4, out_features=1), # Second linear layer
    torch.nn.Sigmoid() # Sigmoid activation function
)
output = model(input)
print("Output sigmoid:", output)

Output sigmoid: tensor([0.3701], grad_fn=<SigmoidBackward0>)


In [9]:
import torch

score = torch.tensor([[0.8]])
# Create a sigmoid function and apply it on the score tensor
sigmoid = torch.nn.Sigmoid()
probability = sigmoid(score)
print("Probability:", probability)

Probability: tensor([[0.6900]])


## Training Neural Network

### Forward pass