# Introduction to Deep Learning with PyTorch

## Introduction to PyTorch

### Tensors

In [4]:
import numpy as np
import torch

array = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(array)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

np_array = np.array(array)
np_tensor = torch.from_numpy(np_array)
print(np_tensor)

torch.Size([2, 3])
torch.int64
cpu
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
import torch

a = torch.tensor([[1, 1], [2, 2]])
b = torch.tensor([[2, 2], [3, 3]])
c = torch.tensor([[2, 2, 4], [3, 3, 5]])

print(a + b)
print(a * b)
print(a + c)

tensor([[3, 3],
        [5, 5]])
tensor([[2, 2],
        [6, 6]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [8]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)
print(tensor_a)
# Display the tensor device
print(tensor_a.device)
# Display the tensor data type
print(tensor_a.dtype)

tensor([1, 2, 3, 4])
cpu
torch.int64


In [10]:
import numpy as np
import torch

array_a = np.array([
    [1, 1, 1],
    [2, 3, 4],
    [4, 5, 6]
])

array_b = np.array([
    [7, 5, 4],
    [2, 2, 8],
    [6, 3, 8]
])

# Create two tensors from the arrays
tensor_a = torch.from_numpy(array_a)
tensor_b = torch.from_numpy(array_b)

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c with tensor_d
tensor_e = tensor_c + tensor_d
print(tensor_e)

tensor([[ 1,  1,  1],
        [ 4,  7, 28],
        [22, 17, 46]])


### Neural Network

In [12]:
import torch

# Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

# Define first linear layer
linear_layer = torch.nn.Linear(in_features=3, out_features=2)

# Pass input through linear layer
output = linear_layer(input_tensor)
print(output)

tensor([[-0.1012,  0.0439]], grad_fn=<AddmmBackward0>)
