<a href="https://colab.research.google.com/github/MengOonLee/Deep_learning/blob/master/TensorFlow2/Tutorial/Customising_TensorFlow2_models/Neural_translation/Neural_translation_English_German.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Capstone Project
## Neural translation model
### Instructions

In this notebook, you will create a neural network that translates from English to German. You will use concepts from throughout this course, including building more flexible model architectures, freezing layers, data processing pipeline and sequence modelling.

This project is peer-assessed. Within this notebook you will find instructions in each section for how to complete the project. Pay close attention to the instructions as the peer review will be carried out according to a grading rubric that checks key parts of the project instructions. Feel free to add extra cells into the notebook as required.

### How to submit

When you have completed the Capstone project notebook, you will submit a pdf of the notebook for peer review. First ensure that the notebook has been fully executed from beginning to end, and all of the cell outputs are visible. This is important, as the grading rubric depends on the reviewer being able to view the outputs of your notebook. Save the notebook as a pdf (you could download the notebook with File -> Download .ipynb, open the notebook locally, and then File -> Download as -> PDF via LaTeX), and then submit this pdf for review.

### Let's get started!

We'll start by running some imports, and loading the dataset. For this project you are free to make further imports throughout the notebook as you wish. 

In [1]:
import tensorflow as tf
import tensorflow_hub as hub
import unicodedata
import re
import os
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Layer, Masking, LSTM
from tensorflow.keras.models import Model

![Flags overview image](https://github.com/MengOonLee/Deep_learning/blob/master/TensorFlow2/Tutorial/image/neural_translation/germany_uk_flags.png?raw=1)

For the capstone project, you will use a language dataset from http://www.manythings.org/anki/ to build a neural translation model. This dataset consists of over 200,000 pairs of sentences in English and German. In order to make the training quicker, we will restrict to our dataset to 20,000 pairs. Feel free to change this if you wish - the size of the dataset used is not part of the grading rubric.

Your goal is to develop a neural translation model from English to German, making use of a pre-trained English word embedding module.

#### Import the data

The dataset is available for download as a zip file at the following link:

https://drive.google.com/open?id=1KczOciG7sYY7SB9UlBeRP1T9659b121Q

You should store the unzipped folder in local drive for use in this Colab notebook.

In [2]:
if not os.path.exists("./data"):
    os.makedirs("./data")

In [3]:
%%bash

fileid="1KczOciG7sYY7SB9UlBeRP1T9659b121Q"
filename="./data/deu.txt"
curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}" > /dev/null
curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' ./cookie`&id=${fileid}" -o ${filename}

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0    273      0 --:--:--  0:00:01 --:--:--   273
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 29.9M    0 29.9M    0     0  15.3M      0 --:--:--  0:00:01 --:--:-- 15.3M


In [4]:
# Run this cell to load the dataset

NUM_EXAMPLES = 20000
data_examples = []
with open('data/deu.txt', 'r', encoding='utf8') as f:
    for line in f.readlines():
        if len(data_examples) < NUM_EXAMPLES:
            data_examples.append(line)
        else:
            break

In [5]:
# These functions preprocess English and German sentences

def unicode_to_ascii(s):
    return ''.join(c for c in unicodedata.normalize('NFD', s) 
        if unicodedata.category(c) != 'Mn')

def preprocess_sentence(sentence):
    sentence = sentence.lower().strip()
    sentence = re.sub(r"ü", 'ue', sentence)
    sentence = re.sub(r"ä", 'ae', sentence)
    sentence = re.sub(r"ö", 'oe', sentence)
    sentence = re.sub(r'ß', 'ss', sentence)
    
    sentence = unicode_to_ascii(sentence)
    sentence = re.sub(r"([?.!,])", r" \1 ", sentence)
    sentence = re.sub(r"[^a-z?.!,']+", " ", sentence)
    sentence = re.sub(r'[" "]+', " ", sentence)
    
    return sentence.strip()

#### The custom translation model
The following is a schematic of the custom translation model architecture you will develop in this project.

![Model Schematic](https://github.com/MengOonLee/Deep_learning/blob/master/TensorFlow2/Tutorial/image/neural_translation/neural_translation_model.png?raw=1)

Key:
![Model key](https://github.com/MengOonLee/Deep_learning/blob/master/TensorFlow2/Tutorial/image/neural_translation/neural_translation_model_key.png?raw=1)

The custom model consists of an encoder RNN and a decoder RNN. The encoder takes words of an English sentence as input, and uses a pre-trained word embedding to embed the words into a 128-dimensional space. To indicate the end of the input sentence, a special end token (in the same 128-dimensional space) is passed in as an input. This token is a TensorFlow Variable that is learned in the training phase (unlike the pre-trained word embedding, which is frozen).

The decoder RNN takes the internal state of the encoder network as its initial state. A `<start>` token is passed in as the first input, which is embedded using a learned German word embedding. The decoder RNN then makes a prediction for the next German word, which during inference is then passed in as the following input, and this process is repeated until the special `<end>` token is emitted from the decoder.

## 1. Text preprocessing
* Create separate lists of English and German sentences, and preprocess them using the `preprocess_sentence` function provided for you above.
* Add a special `"<start>"` and `"<end>"` token to the beginning and end of every German sentence.
* Use the Tokenizer class from the `tf.keras.preprocessing.text` module to tokenize the German sentences, ensuring that no character filters are applied. _Hint: use the Tokenizer's "filter" keyword argument._
* Print out at least 5 randomly chosen examples of (preprocessed) English and German sentence pairs. For the German sentence, print out the text (with start and end tokens) as well as the tokenized sequence.
* Pad the end of the tokenized German sequences with zeros, and batch the complete set of sequences into one numpy array.

In [6]:
def create_sentence(data):
    """
    Clean the input and return sentence pairs.
    """
    sentence_pairs = [[preprocess_sentence(w) for w in l.split('\t')][:2] 
        for l in data]

    return zip(*sentence_pairs)

# get pairs
en_sentence, ge_sentence = create_sentence(data_examples)
# show last 5 pairs
for pair in zip(en_sentence[-5:], ge_sentence[-5:]):
    print(pair)

("i've been working .", 'ich war arbeiten .')
("i've bought a car .", 'ich habe ein auto gekauft .')
("i've come for tom .", 'ich bin fuer tom gekommen .')
("i've done nothing .", 'ich habe nichts getan .')
("i've eaten enough .", 'ich habe genug gegessen .')


In [7]:
def add_start_end(sentences):
    """
    Adding a start and end token to the sentence so that the
    model know when to start and stop predicting.
    """
    
    return ["<start> " + s + " <end>" for s in sentences]

ge_sentence = add_start_end(ge_sentence)
ge_sentence[-5:]

['<start> ich war arbeiten . <end>',
 '<start> ich habe ein auto gekauft . <end>',
 '<start> ich bin fuer tom gekommen . <end>',
 '<start> ich habe nichts getan . <end>',
 '<start> ich habe genug gegessen . <end>']

In [8]:
def create_tokenizer(sentences):
    """
    Create and return a Tokenizer.
    """
    tokenizer = Tokenizer(filters='')
    tokenizer.fit_on_texts(sentences)

    return tokenizer

# Build the German tokenizer vocabulary
ge_tokenizer = create_tokenizer(ge_sentence)
# Tokenize the German sentences
ge_sequence = ge_tokenizer.texts_to_sequences(ge_sentence)
ge_sequence[-5:]

[[1, 4, 24, 252, 3, 2],
 [1, 4, 18, 19, 82, 280, 3, 2],
 [1, 4, 15, 77, 5, 276, 3, 2],
 [1, 4, 18, 108, 182, 3, 2],
 [1, 4, 18, 480, 217, 3, 2]]

In [9]:
# Randomly select 5 examples of English and German sentence pairs
inx = np.random.choice(len(en_sentence), 5, replace=False)

for n, i in enumerate(inx):
    print(n, en_sentence[i])
    print(n, ge_sentence[i], ge_sequence[i])

0 i like australia .
0 <start> ich mag australien . <end> [1, 4, 51, 3041, 3, 2]
1 you're useless .
1 <start> ihr seid nutzlos . <end> [1, 27, 73, 923, 3, 2]
2 tom never talked .
2 <start> tom hat nie geredet . <end> [1, 5, 16, 155, 2133, 3, 2]
3 where's your bag ?
3 <start> wo ist deine tasche ? <end> [1, 83, 6, 117, 398, 7, 2]
4 look out there .
4 <start> pass auf da draussen . <end> [1, 807, 29, 63, 243, 3, 2]


In [10]:
def post_pad(sequences):
    """
    Pad each sequence to a maximum length.
    """

    return pad_sequences(sequences, padding='post')

ge_padded = post_pad(ge_sequence)
ge_padded[-5:]

array([[  1,   4,  24, 252,   3,   2,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  1,   4,  18,  19,  82, 280,   3,   2,   0,   0,   0,   0,   0,
          0],
       [  1,   4,  15,  77,   5, 276,   3,   2,   0,   0,   0,   0,   0,
          0],
       [  1,   4,  18, 108, 182,   3,   2,   0,   0,   0,   0,   0,   0,
          0],
       [  1,   4,  18, 480, 217,   3,   2,   0,   0,   0,   0,   0,   0,
          0]], dtype=int32)

## 2. Prepare the data with tf.data.Dataset objects

#### Load the embedding layer
As part of the dataset preproceessing for this project, you will use a pre-trained English word embedding module from TensorFlow Hub. The URL for the module is https://tfhub.dev/google/tf2-preview/nnlm-en-dim128-with-normalization/1.

This embedding takes a batch of text tokens in a 1-D tensor of strings as input. It then embeds the separate tokens into a 128-dimensional space. 

The code to load and test the embedding layer is provided for you below.

**NB:** This model can also be used as a sentence embedding module. The module will process each token by removing punctuation and splitting on spaces. It then averages the word embeddings over a sentence to give a single embedding vector. However, we will use it only as a word embedding module, and will pass each word in the input sentence as a separate token.

In [11]:
# Load embedding module from Tensorflow Hub
embed_dim=128
embedding_layer = hub.KerasLayer("https://tfhub.dev/google/tf2-preview/nnlm-en-dim128/1", 
    output_shape=[embed_dim], input_shape=[], dtype=tf.string)

In [12]:
# Test the layer

embedding_layer(tf.constant(["these", "aren't", "the", "droids", "you're", "looking", "for"])).shape

TensorShape([7, 128])

You should now prepare the training and validation Datasets.

* Create a random training and validation set split of the data, reserving e.g. 20% of the data for validation (NB: each English dataset example is a single sentence string, and each German dataset example is a sequence of padded integer tokens).
* Load the training and validation sets into a tf.data.Dataset object, passing in a tuple of English and German data for both training and validation sets.
* Create a function to map over the datasets that splits each English sentence at spaces. Apply this function to both Dataset objects using the map method. _Hint: look at the tf.strings.split function._
* Create a function to map over the datasets that embeds each sequence of English words using the loaded embedding layer/model. Apply this function to both Dataset objects using the map method.
* Create a function to filter out dataset examples where the English sentence is greater than or equal to than 13 (embedded) tokens in length. Apply this function to both Dataset objects using the filter method.
* Create a function to map over the datasets that pads each English sequence of embeddings with some distinct padding value before the sequence, so that each sequence is length 13. Apply this function to both Dataset objects using the map method. _Hint: look at the tf.pad function. You can extract a Tensor shape using tf.shape; you might also find the tf.math.maximum function useful._
* Batch both training and validation Datasets with a batch size of 16.
* Print the `element_spec` property for the training and validation Datasets. 
* Using the Dataset `.take(1)` method, print the shape of the English data example from the training Dataset.
* Using the Dataset `.take(1)` method, print the German data example Tensor from the validation Dataset.

In [13]:
# Create a random training and validation sets using an 80-20 split
en_train, en_valid, ge_train, ge_valid = train_test_split(
    en_sentence, ge_padded, test_size=0.2)

# Examine the shape of data
print("The shape of training dataset:")
print(f"English: {np.array(en_train).shape} \t German: {ge_train.shape}")
print("The shape of validation dataset:")
print(f"English: {np.array(en_valid).shape} \t German: {ge_valid.shape}")


The shape of training dataset:
English: (16000,) 	 German: (16000, 14)
The shape of validation dataset:
English: (4000,) 	 German: (4000, 14)


In [14]:
def create_dataset(input, target):
    """
    Takes an input language, and a corresponding target language 
    to create a tf.data.Dataset object with these input and target.
    """

    return tf.data.Dataset.from_tensor_slices((input, target))

# Create Dataset object for both training and vailidation sets
train_dataset = create_dataset(en_train, ge_train)
valid_dataset = create_dataset(en_valid, ge_valid)

# # Print the first 5 elements of the Dataset
for elem in iter(train_dataset.take(5)):
    print(elem[0].numpy(), elem[1].numpy())

b'tom looked sharp .' [   1    5  110 5281   41    3    2    0    0    0    0    0    0    0]
b'come down here .' [  1 180  33 946   9   2   0   0   0   0   0   0   0   0]
b"i'll take him ." [  1   4 380  44   3   2   0   0   0   0   0   0   0   0]
b"don't cheat ." [   1 1834   12    3    2    0    0    0    0    0    0    0    0    0]
b"don't ask ." [  1 374  12   3   2   0   0   0   0   0   0   0   0   0]


In [15]:
def map_split(x, _):
    """
    Splits each English sentence at spaces.
    """

    return (tf.strings.split(x, sep=' '), _)

# Map the function over the both Dataset objects. 
train_dataset = train_dataset.map(map_split)
valid_dataset = valid_dataset.map(map_split)

# # Print the first 5 elements of the Dataset
for elem in iter(train_dataset.take(5)):
    print(elem[0].numpy(), elem[1].numpy())

[b'tom' b'looked' b'sharp' b'.'] [   1    5  110 5281   41    3    2    0    0    0    0    0    0    0]
[b'come' b'down' b'here' b'.'] [  1 180  33 946   9   2   0   0   0   0   0   0   0   0]
[b"i'll" b'take' b'him' b'.'] [  1   4 380  44   3   2   0   0   0   0   0   0   0   0]
[b"don't" b'cheat' b'.'] [   1 1834   12    3    2    0    0    0    0    0    0    0    0    0]
[b"don't" b'ask' b'.'] [  1 374  12   3   2   0   0   0   0   0   0   0   0   0]


In [16]:
def map_embed(x, _):
    """
    Embeds each sequence of English words using the loaded embedding layer.
    """

    return (embedding_layer(x), _)

# Map the function over the both Dataset objects. 
train_dataset = train_dataset.map(map_embed)
valid_dataset = valid_dataset.map(map_embed)

# Print the element_spec property for both Datasets
print("The training Dataset's element_spec property:")
print(train_dataset.element_spec)
print("The validation Dataset's element_spec property:")
print(valid_dataset.element_spec)

The training Dataset's element_spec property:
(TensorSpec(shape=(None, 128), dtype=tf.float32, name=None), TensorSpec(shape=(14,), dtype=tf.int32, name=None))
The validation Dataset's element_spec property:
(TensorSpec(shape=(None, 128), dtype=tf.float32, name=None), TensorSpec(shape=(14,), dtype=tf.int32, name=None))


In [17]:
def filter_length(x, _):
    """
    Filter out dataset examples where the English sentence is 
    greater than or equal to 13 (embedded) tokens in length.
    """

    return len(x)<13

# Filter over the both Dataset objects.
train_dataset = train_dataset.filter(filter_length)
valid_dataset = valid_dataset.filter(filter_length)

# Print the element_spec property for both Datasets
print("The training Dataset's element_spec property:")
print(train_dataset.element_spec)
print("The validation Dataset's element_spec property:")
print(valid_dataset.element_spec)

The training Dataset's element_spec property:
(TensorSpec(shape=(None, 128), dtype=tf.float32, name=None), TensorSpec(shape=(14,), dtype=tf.int32, name=None))
The validation Dataset's element_spec property:
(TensorSpec(shape=(None, 128), dtype=tf.float32, name=None), TensorSpec(shape=(14,), dtype=tf.int32, name=None))


In [18]:
def map_pad_embedding(x, _):
    """
    Pads each English sequence of embeddings with some distinct
    padding value before the sequence, so that each sequence is
    length 13.
    """
    pad_size = tf.math.maximum(0, 13 - tf.shape(x)[0])
    paddings = tf.concat(([[pad_size, 0]], [[0, 0]]), axis=0)
    padded = tf.pad(x, paddings, "CONSTANT")

    return (tf.reshape(padded, [13, 128]), _)

# Map the function over the both Dataset objects. 
train_dataset = train_dataset.map(map_pad_embedding)
valid_dataset = valid_dataset.map(map_pad_embedding)

# Print the element_spec property for both Datasets
print("The training Dataset's element_spec property:")
print(train_dataset.element_spec)
print("The validation Dataset's element_spec property:")
print(valid_dataset.element_spec)

The training Dataset's element_spec property:
(TensorSpec(shape=(13, 128), dtype=tf.float32, name=None), TensorSpec(shape=(14,), dtype=tf.int32, name=None))
The validation Dataset's element_spec property:
(TensorSpec(shape=(13, 128), dtype=tf.float32, name=None), TensorSpec(shape=(14,), dtype=tf.int32, name=None))


In [19]:
def create_batch(dataset, batch_size):
  """
  Batch the dataset using the batch_size argument, 
  setting drop_remainder to True.
  """

  return dataset.batch(batch_size, drop_remainder=True)

# Batch the both Datasets with a batch size of 16.
batch_size = 16
train_dataset = create_batch(train_dataset, batch_size)
valid_dataset = create_batch(valid_dataset, batch_size)

# Print the element_spec property for both Datasets
print("The training Dataset's element_spec property:")
print(train_dataset.element_spec)
print("The validation Dataset's element_spec property:")
print(valid_dataset.element_spec)

The training Dataset's element_spec property:
(TensorSpec(shape=(16, 13, 128), dtype=tf.float32, name=None), TensorSpec(shape=(16, 14), dtype=tf.int32, name=None))
The validation Dataset's element_spec property:
(TensorSpec(shape=(16, 13, 128), dtype=tf.float32, name=None), TensorSpec(shape=(16, 14), dtype=tf.int32, name=None))


In [25]:
# Print the shape of the English data example from the training Dataset
en_train_batch, ge_train_batch = next(iter(train_dataset.take(1)))
print("The shape of English data example from the training Dataset:", 
    en_train_batch.shape)

# Print the German data example Tensor from the validation Dataset
en_valid_batch, ge_valid_batch = next(iter(valid_dataset.take(1)))
print("The German data example Tensor from the validation Dataset:\n", 
    ge_valid_batch.numpy())

The shape of English data example from the training Dataset: (16, 13, 128)
The German data example Tensor from the validation Dataset:
 [[   1    8    6   21 4829    3    2    0    0    0    0    0    0    0]
 [   1   17   35   10   12    3    2    0    0    0    0    0    0    0]
 [   1   10   24  422    3    2    0    0    0    0    0    0    0    0]
 [   1   21    6   70  232    3    2    0    0    0    0    0    0    0]
 [   1   10    6   19 2144  214    3    2    0    0    0    0    0    0]
 [   1   42    6   27  781    7    2    0    0    0    0    0    0    0]
 [   1  253   27   31   12   90    7    2    0    0    0    0    0    0]
 [   1   14    6   12   50  772    3    2    0    0    0    0    0    0]
 [   1 3122   11  820  125    3    2    0    0    0    0    0    0    0]
 [   1  184   52  160    5   36    3    2    0    0    0    0    0    0]
 [   1    4   39   10  433    3    2    0    0    0    0    0    0    0]
 [   1   47  517    6 3653    3    2    0    0    0    0    0

## 3. Create the custom layer
You will now create a custom layer to add the learned end token embedding to the encoder model:

![Encoder schematic](https://github.com/MengOonLee/Deep_learning/blob/master/TensorFlow2/Tutorial/image/neural_translation/neural_translation_model_encoder.png?raw=1)

You should now build the custom layer.
* Using layer subclassing, create a custom layer that takes a batch of English data examples from one of the Datasets, and adds a learned embedded ‘end’ token to the end of each sequence. 
* This layer should create a TensorFlow Variable (that will be learned during training) that is 128-dimensional (the size of the embedding space). _Hint: you may find it helpful in the call method to use the tf.tile function to replicate the end token embedding across every element in the batch._
* Using the Dataset `.take(1)` method, extract a batch of English data examples from the training Dataset and print the shape. Test the custom layer by calling the layer on the English data batch Tensor and print the resulting Tensor shape (the layer should increase the sequence length by one).

In [26]:
class EndToken(Layer):
    """
    A custom layer takes a batch of English data examples from Datasets, 
    and adds a learned embedded 'end' token to the end of each sequence.
    """

    def __init__(self, embed_dim, **kwargs):
        super(EndToken, self).__init__(**kwargs)
        end_init = tf.random_normal_initializer(seed=42)
        self.end_var = tf.Variable(end_init(shape=(1, 1, embed_dim), 
            dtype="float32"), trainable=True, name="end")
        
    def build(self, input_shape):
        self.end_token = tf.tile(self.end_var, [input_shape[0], 1, 1])

    def call(self, inputs):
        return tf.concat([inputs, self.end_token], axis=1)

# Instantiate the custom layer object and 
# print the number of trainable variables
end_token_layer = EndToken(embed_dim)
print('Number of trainable variables:', 
    len(end_token_layer.trainable_variables))

Number of trainable variables: 1


In [27]:
# Print the shape for a batch of the English data examples 
# from the training Dataset
en_train_batch, ge_train_batch = next(iter(train_dataset.take(1)))
print("English training Dataset's shape before adding the end token:", 
    en_train_batch.shape)

English training Dataset's shape before adding the end token: (16, 13, 128)


In [29]:
# Test the custom layer on the English data batch tensor 
# and print the resulting tensor shape
print("English training Dataset's shape after adding the end token:", 
    end_token_layer(en_train_batch).shape)

English training Dataset's shape after adding the end token: (16, 14, 128)


## 4. Build the encoder network
The encoder network follows the schematic diagram above. You should now build the RNN encoder model.
* Using the functional API, build the encoder network according to the following spec:
    * The model will take a batch of sequences of embedded English words as input, as given by the Dataset objects.
    * The next layer in the encoder will be the custom layer you created previously, to add a learned end token embedding to the end of the English sequence.
    * This is followed by a Masking layer, with the `mask_value` set to the distinct padding value you used when you padded the English sequences with the Dataset preprocessing above.
    * The final layer is an LSTM layer with 512 units, which also returns the hidden and cell states.
    * The encoder is a multi-output model. There should be two output Tensors of this model: the hidden state and cell states of the LSTM layer. The output of the LSTM layer is unused.
* Using the Dataset `.take(1)` method, extract a batch of English data examples from the training Dataset and test the encoder model by calling it on the English data Tensor, and print the shape of the resulting Tensor outputs.
* Print the model summary for the encoder network.

In [44]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Masking, LSTM

inputs = Input(shape=(13, 128))
h = Masking(mask_value=0.0)(inputs)
outputs, hidden, cell = LSTM(512, return_sequences=True, return_states)

model = Model(inputs, h)
model.summary()

# y = train_dataset.map(lambda x, _: (masking_layer(x), _))

for elem in train_dataset.take(1):
    x = elem[0]
    x = model(x)
    print(x._keras_mask)

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 13, 128)]         0         
_________________________________________________________________
masking_13 (Masking)         (None, 13, 128)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
tf.Tensor(
[[False False False False False False False False  True  True  True  True
   True]
 [False False False False False False False False False False  True  True
   True]
 [False False False False False False False False False False  True  True
   True]
 [False False False False False False False False False  True  True  True
   True]
 [False False False False False False False False False  True  True  True
   True]
 [False False False False False False False False  True  True  True  True
   True]
 [False False Fals

In [ ]:
class Encoder(Model):
    """
    A RNN encoder model takes a batch of sequences of embedded English words 
    from the Dataset object, and adds a learned end token embedding to the end 
    of the English sequence using the EndToken layer.
    """

    def __init__(self, embed_dim, enc_units, **kwargs):
        super(Encoder, self).__init__(**kwargs)
        # Define layers
        self.end_token = EndToken(embed_dim)
        self.mask = Masking(mask_value=0.0)
        self.lstm_layer = LSTM(enc_units, 
            return_sequences=True, return_state=True)

    def call(self, x, hidden):
        # Define forward pass
        x = self.end_token(x)
        x = self.mask(x)
        _, h, c = self.lstm_layer(x, initial_state=hidden)
        return h, c

# Instantiate the model object
encoder_model = Encoder(embed_dim)

In [ ]:
# Test the encoder model on the English data tensor from the training Dataset
# and print the resulting tensor shape
for elem in encoder_model(train_dataset).take(1):
    print(f"English training Dataset's shape after test the encoder model: {elem[0].shape}")

In [ ]:
# Print the model summary for the encoder network
print("The encoder model summary:")
print(encoder_model.summary())

## 5. Build the decoder network
The decoder network follows the schematic diagram below.

![Decoder schematic](https://github.com/MengOonLee/Deep_learning/blob/master/TensorFlow2/Tutorial/image/neural_translation/neural_translation_model_decoder.png?raw=1)

You should now build the RNN decoder model.
* Using Model subclassing, build the decoder network according to the following spec:
    * The initializer should create the following layers:
        * An Embedding layer with vocabulary size set to the number of unique German tokens, embedding dimension 128, and set to mask zero values in the input.
        * An LSTM layer with 512 units, that returns its hidden and cell states, and also returns sequences.
        * A Dense layer with number of units equal to the number of unique German tokens, and no activation function.
    * The call method should include the usual `inputs` argument, as well as the additional keyword arguments `hidden_state` and `cell_state`. The default value for these keyword arguments should be `None`.
    * The call method should pass the inputs through the Embedding layer, and then through the LSTM layer. If the `hidden_state` and `cell_state` arguments are provided, these should be used for the initial state of the LSTM layer. _Hint: use the_ `initial_state` _keyword argument when calling the LSTM layer on its input._
    * The call method should pass the LSTM output sequence through the Dense layer, and return the resulting Tensor, along with the hidden and cell states of the LSTM layer.
* Using the Dataset `.take(1)` method, extract a batch of English and German data examples from the training Dataset. Test the decoder model by first calling the encoder model on the English data Tensor to get the hidden and cell states, and then call the decoder model on the German data Tensor and hidden and cell states, and print the shape of the resulting decoder Tensor outputs.
* Print the model summary for the decoder network.

## 6. Make a custom training loop
You should now write a custom training loop to train your custom neural translation model.
* Define a function that takes a Tensor batch of German data (as extracted from the training Dataset), and returns a tuple containing German inputs and outputs for the decoder model (refer to schematic diagram above).
* Define a function that computes the forward and backward pass for your translation model. This function should take an English input, German input and German output as arguments, and should do the following:
    * Pass the English input into the encoder, to get the hidden and cell states of the encoder LSTM.
    * These hidden and cell states are then passed into the decoder, along with the German inputs, which returns a sequence of outputs (the hidden and cell state outputs of the decoder LSTM are unused in this function).
    * The loss should then be computed between the decoder outputs and the German output function argument.
    * The function returns the loss and gradients with respect to the encoder and decoder’s trainable variables.
    * Decorate the function with `@tf.function`
* Define and run a custom training loop for a number of epochs (for you to choose) that does the following:
    * Iterates through the training dataset, and creates decoder inputs and outputs from the German sequences.
    * Updates the parameters of the translation model using the gradients of the function above and an optimizer object.
    * Every epoch, compute the validation loss on a number of batches from the validation and save the epoch training and validation losses.
* Plot the learning curves for loss vs epoch for both training and validation sets.

_Hint: This model is computationally demanding to train. The quality of the model or length of training is not a factor in the grading rubric. However, to obtain a better model we recommend using the GPU accelerator hardware on Colab._

## 7. Use the model to translate
Now it's time to put your model into practice! You should run your translation for five randomly sampled English sentences from the dataset. For each sentence, the process is as follows:
* Preprocess and embed the English sentence according to the model requirements.
* Pass the embedded sentence through the encoder to get the encoder hidden and cell states.
* Starting with the special  `"<start>"` token, use this token and the final encoder hidden and cell states to get the one-step prediction from the decoder, as well as the decoder’s updated hidden and cell states.
* Create a loop to get the next step prediction and updated hidden and cell states from the decoder, using the most recent hidden and cell states. Terminate the loop when the `"<end>"` token is emitted, or when the sentence has reached a maximum length.
* Decode the output token sequence into German text and print the English text and the model's German translation.