<a href="https://colab.research.google.com/github/MengOonLee/Deep_learning/blob/master/TensorFlow2/Tutorial/TFDataset_pandas_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Datasets from different sources

In this reading notebook, we will explore a few of the ways in which we can load data into a `tf.data.Dataset` object.

In [1]:
import tensorflow as tf
print(tf.__version__)

2.3.0


## The `from_tensor_slices` and `from_tensors` methods

We will start by looking at the `from_tensor_slices` and the `from_tensors` methods.

Both static methods are used to create datasets from Tensors or Tensor-like objects, such as numpy arrays or python lists. We can also pass in tuples and dicts of arrays or lists. The main distinction between the `from_tensor_slices` function and the `from_tensors` function is that the `from_tensor_slices` method will interpret the first dimension of the input data as the number of elements in the dataset, whereas the `from_tensors` method always results in a Dataset with a single element, containing the Tensor or tuple of Tensors passed.

In [2]:
# Create a random tensor with shape (3, 2)

example_tensor = tf.random.uniform([3,2])
print(example_tensor.shape)

(3, 2)


In [3]:
# Create two Datasets, using each static method

dataset1 = tf.data.Dataset.from_tensor_slices(example_tensor)
dataset2 = tf.data.Dataset.from_tensors(example_tensor)

In [4]:
# Print the element_spec for each

print(dataset1.element_spec)
print(dataset2.element_spec)

TensorSpec(shape=(2,), dtype=tf.float32, name=None)
TensorSpec(shape=(3, 2), dtype=tf.float32, name=None)


As seen above, creating the Dataset using the `from_tensor_slices` method slices the given array or Tensor along the first dimension to produce a set of elements for the Dataset.

This means that although we could pass any Tensor - or tuple of Tensors - to the `from_tensors` method, the same cannot be said of the `from_tensor_slices` method, which has the additional requirement that each Tensor in the list has the same size in the zeroth dimension.

In [5]:
# Create three Tensors with different shapes

tensor1 = tf.random.uniform([10,2,2])
tensor2 = tf.random.uniform([10,1])
tensor3 = tf.random.uniform([9,2,2])

We cannot create a Dataset using the `from_tensor_slices` method from a list of `tensor1` and `tensor3` since they do not have the same size in the first dimension:

In [6]:
# Try to create a Dataset from tensor1 and tensor3 using from_tensor_slices - this will raise an error

dataset = tf.data.Dataset.from_tensor_slices((tensor1, tensor3))

ValueError: ignored

However, we can of course create a Dataset from this tuple using the `from_tensors` method, which interprets the tuple as a single element.

In [7]:
# Create a Dataset from tensor1 and tensor3 using from_tensors

dataset = tf.data.Dataset.from_tensors((tensor1, tensor3))
dataset.element_spec

(TensorSpec(shape=(10, 2, 2), dtype=tf.float32, name=None),
 TensorSpec(shape=(9, 2, 2), dtype=tf.float32, name=None))

Although `tensor1` and `tensor2` do not have the same shape, or even same rank (number of dimensions), we can still use the `from_tensor_slices` method to form a dataset from a list of these tensors, since they have the same size in the first dimension.

In [8]:
# Create a Dataset from tensor1 and tensor2

dataset = tf.data.Dataset.from_tensor_slices((tensor1, tensor2))
dataset.element_spec

(TensorSpec(shape=(2, 2), dtype=tf.float32, name=None),
 TensorSpec(shape=(1,), dtype=tf.float32, name=None))

In the above, the first dimension was interpreted as the number of elements in the Dataset, as expected.

### Creating Datasets from numpy arrays

We can also use the `from_tensor_slices` and `from_tensors` methods to create Datasets from numpy arrays. In fact, behind the scenes, the numpy array is converted to a set of `tf.constant` operations to populate the Tensor in the TensorFlow graph.

In [9]:
# Create a numpy array dataset

import numpy as np

numpy_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(numpy_array.shape)

(3, 2, 2)


In [10]:
# Create two Datasets, using each static method

dataset1 = tf.data.Dataset.from_tensor_slices(numpy_array)
dataset2 = tf.data.Dataset.from_tensors(numpy_array)

print(dataset1.element_spec)
print(dataset2.element_spec)

TensorSpec(shape=(2, 2), dtype=tf.int64, name=None)
TensorSpec(shape=(3, 2, 2), dtype=tf.int64, name=None)


As before, `from_tensors` interprets the entire array as a single element, whereas `from_tensor_slices` slices the array along the first dimension to form the elements.

### Creating Datasets from pandas DataFrames
A pandas DataFrame can be easily converted to a Dataset using the `from_tensor_slices` method. 
#### The Balloons dataset
A pandas DataFrame can be loaded from a CSV file. We will use the [Balloons dataset](https://archive.ics.uci.edu/ml/datasets/Balloons) to demonstrate. This dataset is stored in a CSV file, and contains a list of attributes describing instances of a balloon inflation experiment, such as the colour and size of the balloon, the age of the person who performed the attempted inflation, and the way in which they did it. Finally, there is the target column "Inflated", which is either `T` for True, or `F` for False, indicating whether or not the person managed to inflate the balloon.

#### Import the data

The CSV file for this dataset that is required for this notebook can be downloaded from the following link:

https://drive.google.com/open?id=1bKr-kqhHM9DJBggdmhZ2NFsPX9O4aaYO

You should store the data for use in this Colab notebook.

In [11]:
import os

data_dir = "./data"
if not os.path.exists(data_dir):
    os.makedirs(data_dir)

In [12]:
%%bash

fileid="1bKr-kqhHM9DJBggdmhZ2NFsPX9O4aaYO"
filename="./data/balloon_dataset.csv"
curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}" > /dev/null
curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' ./cookie`&id=${fileid}" -o ${filename}

rm ./cookie

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0   3517      0 --:--:-- --:--:-- --:--:--  3487
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   576  100   576    0     0   1932      0 --:--:-- --:--:-- --:--:--  1932


In [13]:
# Load the CSV file into a Dataframe

import pandas as pd

pandas_dataframe = pd.read_csv('data/balloon_dataset.csv')

In [14]:
# Inspect the data

pandas_dataframe.head()

Colour   Size      Act    Age Inflated
0  YELLOW  SMALL  STRETCH  ADULT        T
1  YELLOW  SMALL  STRETCH  ADULT        T
2  YELLOW  SMALL  STRETCH  CHILD        F
3  YELLOW  SMALL      DIP  ADULT        F
4  YELLOW  SMALL      DIP  CHILD        F

To convert the DataFrame to a Dataset, we first convert the DataFrame to a dictionary. By doing this, we preserve the column names as the dictionary labels.

**Note**: A Dataset can be formed from either a tuple or a dict of Tensors. We saw above a number of Datasets being formed from a tuple. The only distinction for a Dataset formed from a dict is that the Dataset items will be dicts accessed by key, rather than tuples accessed by index.

In [15]:
# Convert the DataFrame to a dict

dataframe_dict = dict(pandas_dataframe)
print(dataframe_dict.keys())

dict_keys(['Colour', 'Size', 'Act', 'Age', 'Inflated'])


We can now run the `from_tensor_slices` method on this `dict` and print the resulting Dataset `element_spec`, as well as an example element. Note that since we formed the Dataset from a `dict`, we see the column (dictionary) names in the `element_spec`.

In [16]:
# Create the Dataset

pandas_dataset = tf.data.Dataset.from_tensor_slices(dataframe_dict)

In [17]:
# View the Dataset element_spec

pandas_dataset.element_spec

{'Act': TensorSpec(shape=(), dtype=tf.string, name=None),
 'Age': TensorSpec(shape=(), dtype=tf.string, name=None),
 'Colour': TensorSpec(shape=(), dtype=tf.string, name=None),
 'Inflated': TensorSpec(shape=(), dtype=tf.string, name=None),
 'Size': TensorSpec(shape=(), dtype=tf.string, name=None)}

In [18]:
# Iterate the Dataset

next(iter(pandas_dataset))

{'Act': <tf.Tensor: shape=(), dtype=string, numpy=b'STRETCH'>,
 'Age': <tf.Tensor: shape=(), dtype=string, numpy=b'ADULT'>,
 'Colour': <tf.Tensor: shape=(), dtype=string, numpy=b'YELLOW'>,
 'Inflated': <tf.Tensor: shape=(), dtype=string, numpy=b'T'>,
 'Size': <tf.Tensor: shape=(), dtype=string, numpy=b'SMALL'>}

## Creating Datasets directly from CSV Files

The TensorFlow experimental library contains a variety of functions and classes contributed by the community that may not be ready for release into the main TensorFlow library in their immediate form, but which may be included in TensorFlow in the future. One such useful experimental function is the `tf.data.experimental.make_csv_dataset` function. This allows us to read CSV data from the disk directly into a Dataset object.

We will run the function on the example CSV file from disk, and specify the batch size and the name of the target column, which is used to structure the Dataset into an `(input, target)` tuple.

**Note:** Because of the ephemeral nature of the `experimental` package, you may well get warnings printed in the console when using a function or class contained in the package for the first time.

In [19]:
# Create the Dataset from the CSV file

csv_dataset = tf.data.experimental.make_csv_dataset(
    'data/balloon_dataset.csv', batch_size=1, label_name='Inflated')

To check that we've loaded our Dataset correctly, let's print the `element_spec`:

In [20]:
# View the Dataset element_spec

csv_dataset.element_spec

(OrderedDict([('Colour', TensorSpec(shape=(1,), dtype=tf.string, name=None)),
              ('Size', TensorSpec(shape=(1,), dtype=tf.string, name=None)),
              ('Act', TensorSpec(shape=(1,), dtype=tf.string, name=None)),
              ('Age', TensorSpec(shape=(1,), dtype=tf.string, name=None))]),
 TensorSpec(shape=(1,), dtype=tf.string, name=None))

In [21]:
# Iterate the Dataset

next(iter(csv_dataset))

(OrderedDict([('Colour',
               <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'PURPLE'], dtype=object)>),
              ('Size',
               <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'LARGE'], dtype=object)>),
              ('Act',
               <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'STRETCH'], dtype=object)>),
              ('Age',
               <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'ADULT'], dtype=object)>)]),
 <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'T'], dtype=object)>)

Note that in the above Dataset, the target column `Inflated` does not have a key, since it is uniquely accessible as the second element of the tuple, whereas the attributes which reside as a dictionary of Tensors in the first element retain their labels so we can distinguish them.

## Further reading and resources

* https://www.tensorflow.org/guide/data
* https://www.tensorflow.org/tutorials/load_data/csv
* https://www.tensorflow.org/tutorials/load_data/pandas_dataframe
* https://www.tensorflow.org/api_docs/python/tf/data/Dataset