<a href="https://colab.research.google.com/github/MengOonLee/Deep_learning/blob/master/TensorFlow/Probabilistic/Distributions/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Broadcasting rules

This reading will introduce you to numpy's broadcasting rules and show how you can use broadcasting when specifying batches of distributions in TensorFlow, as well as with the `prob` and `log_prob` methods.

Broadcasting will also be discussed and demonstrated in the following videos.

In [ ]:
import tensorflow as tf
import tensorflow_probability as tfp

print("TF version:", tf.__version__)
print("TFP version:", tfp.__version__)

TF version: 2.18.0
TFP version: 0.25.0


## Operations on arrays of different sizes in numpy

Numpy operations can be applied to arrays that are not of the same shape, but only if the shapes satisfy certain conditions.

As a demonstration of this, let us add together two arrays of different shapes:

In [1]:
# Add two arrays with different shapes
import numpy as np

a = np.array([[1], [2], [3], [4]], dtype=np.float32)  # shape (4, 1)
b = np.array([0, 1, 2], dtype=np.float32)  # shape (3,)

a + b

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.]], dtype=float32)

This is the addition

    [ [1.],    +  [0., 1., 2.]  
      [2.],  
      [3.],  
      [4.] ]

To execute it, numpy:
1. Aligned the shapes of `a` and `b` on the last axis and prepended 1s to the shape with fewer axes:
        a: 4 x 1     --->    a: 4 x 1
        b:     3     --->    b: 1 x 3
        

2. Checked that the sizes of the axes matched or were equal to 1:
        a: 4 x 1  
        b: 1 x 3
`a` and `b` satisfied this criterion.


3. Stretched both arrays on their 1-valued axes so that their shapes matched, then added them together.  
`a` was replicated 3 times in the second axis, while `b` was replicated 4 times in the first axis.

This meant that the addition in the final step was

    [ [1., 1., 1.],    +  [ [0., 1., 2.],  
      [2., 2., 2.],         [0., 1., 2.],  
      [3., 3., 3.],         [0., 1., 2.],  
      [4., 4., 4.] ]        [0., 1., 2.] ]
      
Addition was then carried out element-by-element, as you can verify by referring back to the output of the code cell above.  
This resulted in an output with shape 4 x 3.


## Numpy's broadcasting rule

Broadcasting rules describe how values should be transmitted when the inputs to an operation do not match.  
In numpy, the broadcasting rule is very simple:
> Prepend 1s to the smaller shape,   
check that the axes of both arrays have sizes that are equal or 1,  
then stretch the arrays in their size-1 axes.

A crucial aspect of this rule is that it does not require the input arrays have the same number of axes.  
Another consequence of it is that a broadcasting output will have the largest size of its inputs in each axis.  
Take the following multiplication as an example:

        a: 3 x 7 x 1  
        b:     1 x 5  
    a * b: 3 x 7 x 5

You can see that the output shape is the maximum of the sizes in each axis.

Numpy's broadcasting rule also does not require that one of the arrays has to be bigger in all axes.  
This is seen in the following example, where `a` is smaller than `b` in its third axis but is bigger in its second axis.

In [2]:
# Multiply two arrays with different shapes
import numpy as np

a = np.array([[[0.01], [0.1]], [[1], [10]]], dtype=np.float32) # shape (2, 2, 1)
b = np.array([[[2, 2]], [[3, 3]]], dtype=np.float32) # shape (2, 1, 2)

a * b # shape (2, 2, 2)

array([[[2.e-02, 2.e-02],
        [2.e-01, 2.e-01]],

       [[3.e+00, 3.e+00],
        [3.e+01, 3.e+01]]], dtype=float32)

Broadcasting behaviour also points to an efficient way to compute an outer product in numpy:

In [3]:
# Use broadcasting to compute an outer product
import numpy as np

a = np.array([-1, 0, 1], dtype=np.float32)
b = np.array([0, 1, 2, 3], dtype=np.float32)

a[..., np.newaxis] * b  # outer product ab^T, where a and b are column vectors

array([[-0., -1., -2., -3.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.]], dtype=float32)

The idea of numpy stretching the arrays in their size-1 axes is useful and is functionally correct. But this is not what numpy literally does behind the scenes, since that would be an inefficient use of memory. Instead, numpy carries out the operation by looping over singleton (size-1) dimensions.

To give you some practise with broadcasting, try predicting the output shapes for the following operations:

In [4]:
# Define three arrays with different shapes
import numpy as np

a = np.array([[1], [2], [3]], dtype=np.float32)
b = np.zeros(shape=(10, 1, 1), dtype=np.float32)
c = np.ones(shape=(4), dtype=np.float32)

In [5]:
# Predict the shape before executing this cell

(a + b).shape

(10, 3, 1)

In [6]:
# Predict the shape before executing this cell

(a*c).shape

(3, 4)

In [7]:
# Predict the shape before executing this cell

(a*b + c).shape

(10, 3, 4)

## Broadcasting for univariate TensorFlow Distributions

The broadcasting rule for TensorFlow is the same as that for numpy. For example, TensorFlow also allows you to specify the parameters of Distribution objects using broadcasting.

What is meant by this can be understood through an example with the univariate normal distribution. Say that we wish to specify a parameter grid for six Gaussians. The parameter combinations to be used, `(loc, scale)`, are:  

    (0, 1)  
    (0, 10)  
    (0, 100)  
    (1, 1)  
    (1, 10)  
    (1, 100)
    
A laborious way of doing this is to explicitly pass each parameter to `tfd.Normal`:

In [8]:
# Define a batch of Normal distributions without broadcasting
import tensorflow as tf
import tensorflow_probability as tfp
tf.keras.utils.set_random_seed(seed=42)

batch_of_normals = tfp.distributions.Normal(
    loc=[0, 0, 0, 1, 1, 1],
    scale=[1, 10, 100, 1, 10, 100])

In [9]:
# Print the distribution and notice the batch and event shapes

batch_of_normals

<tfp.distributions.Normal 'Normal' batch_shape=[6] event_shape=[] dtype=float32>

In [10]:
# Check the parameter values for loc

batch_of_normals.loc

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([0., 0., 0., 1., 1., 1.], dtype=float32)>

In [11]:
# Check the parameter values for scale

batch_of_normals.scale

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([  1.,  10., 100.,   1.,  10., 100.], dtype=float32)>

A more succinct way to create a batch of distributions for this parameter grid is to use broadcasting.  
Consider what would happen if we were to broadcast these arrays according the rule discussed earlier:
    
    loc = [ [0.],
            [1.] ]
    scale = [1., 10., 100.]
    
The shapes would be stretched according to

    loc:   2 x 1 ---> 2 x 3
    scale: 1 x 3 ---> 2 x 3
    
resulting in

    loc = [ [0., 0., 0.],
            [1., 1., 1.] ]
    scale = [ [1., 10., 100.],
              [1., 10., 100.] ]
              
which are compatible with the `loc` and `scale` arguments of `tfd.Normal`.  
Sure enough, this is precisely what TensorFlow does:

In [12]:
# Define a batch of Normal distributions with broadcasting
import tensorflow as tf
import tensorflow_probability as tfp
tf.keras.utils.set_random_seed(seed=42)

loc = [[0], [1]]
scale = [1, 10, 100]

another_batch_of_normals = tfp.distributions.Normal(
    loc=loc, scale=scale)

In [13]:
# Print the distribution and notice the batch and event shapes

another_batch_of_normals

<tfp.distributions.Normal 'Normal' batch_shape=[2, 3] event_shape=[] dtype=float32>

In [14]:
# The stored loc parameter values are what you pass in, not what is used after broadcasting

another_batch_of_normals.loc

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [1.]], dtype=float32)>

In [15]:
# The stored scale parameter values are what you pass in, not what is used after broadcasting

another_batch_of_normals.scale

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([  1.,  10., 100.], dtype=float32)>

In summary, TensorFlow broadcasts parameter arrays: it stretches them according to the broadcasting rule, then creates a distribution on an element-by-element basis.

#### Broadcasting with `prob` and `log_prob` methods

When using `prob` and  `log_prob` with broadcasting, we follow the same principles as before. Let's make a new batch of normals as before but with means which are centered at different locations to help distinguish the results we get.

In [16]:
# Define a batch of Normal distributions with broadcasting
import tensorflow as tf
import tensorflow_probability as tfp
tf.keras.utils.set_random_seed(seed=42)

loc = [[0], [10]]
scale = [1, 1, 1]

another_batch_of_normals = tfp.distributions.Normal(
    loc=loc, scale=scale)
another_batch_of_normals

<tfp.distributions.Normal 'Normal' batch_shape=[2, 3] event_shape=[] dtype=float32>

We can feed in samples of any shape as long as it can be broadcast agasint our batch shape for this example.

In [17]:
# Use broadcasting along the second axis with the prob method
import tensorflow as tf
tf.keras.utils.set_random_seed(seed=42)

sample = tf.random.uniform(shape=(2, 1),
    dtype=tf.float32)
another_batch_of_normals.prob(value=sample)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3.1989583e-01, 3.1989583e-01, 3.1989583e-01],
       [5.7441017e-21, 5.7441017e-21, 5.7441017e-21]], dtype=float32)>

Or boradcasting along the first axis instead:

In [18]:
# Use broadcasting along the first axis with the prob method
import tensorflow as tf
tf.keras.utils.set_random_seed(seed=42)

sample = tf.random.uniform(shape=(1, 3),
    dtype=tf.float32)
another_batch_of_normals.prob(value=sample)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3.1989583e-01, 3.6197433e-01, 3.7486044e-01],
       [4.7472477e-20, 5.7441017e-21, 2.4643045e-21]], dtype=float32)>

Or even both axes:

In [19]:
# Use broadcasting along both axes with the prob method
import tensorflow as tf
tf.keras.utils.set_random_seed(seed=42)

sample = tf.random.uniform(shape=(1, 1),
    dtype=tf.float32)
another_batch_of_normals.prob(value=sample)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3.1989583e-01, 3.1989583e-01, 3.1989583e-01],
       [4.7472477e-20, 4.7472477e-20, 4.7472477e-20]], dtype=float32)>

`log_prob` works in the exact same way with broadcasting. We can replace `prob` with `log_prob` in any of the previous examples:

In [20]:
# Use broadcasting along the first axis with the log_prob method
import tensorflow as tf
tf.keras.utils.set_random_seed(seed=42)

sample = tf.random.uniform(shape=(1, 3),
    dtype=tf.float32)
another_batch_of_normals.log_prob(value=sample)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ -1.1397599,  -1.016182 ,  -0.9812015],
       [-44.494137 , -46.606113 , -47.452377 ]], dtype=float32)>

## Broadcasting for multivariate TensorFlow distributions

Broadcasting behaviour for multivariate distributions is only a little more sophisticated than it is for univariate distributions.

Recall that `MultivariateNormalDiag` has two parameter arguments: `loc` and `scale_diag`. When specifying a single distribution, these arguments are vectors of the same length:

In [21]:
# Define a multivariate Gaussian distribution without broadcasting
import tensorflow as tf
import tensorflow_probability as tfp
tf.keras.utils.set_random_seed(seed=42)

single_mvt_normal = tfp.distributions.MultivariateNormalDiag(
    loc=[0], scale_diag=[1, 0.5])
single_mvt_normal

<tfp.distributions.MultivariateNormalDiag 'MultivariateNormalDiag' batch_shape=[] event_shape=[2] dtype=float32>

In [22]:
# Print the loc parameter

single_mvt_normal.loc

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [23]:
# Print the covariance matrix - the diagonal is scale_diag^2

single_mvt_normal.covariance()

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.  , 0.  ],
       [0.  , 0.25]], dtype=float32)>

The size of the final axis of the inputs determines the event shape for each distribution in the batch.  This means that if we pass
    
    loc = [ [0., 0.],
            [1., 1.] ]
    scale_diag = [1., 0.5]
    
such that

    loc:        2 x 2
    scale_diag: 1 x 2
                    ^ final dimension is interpreted as event dimension
                ^ other dimensions are interpreted as batch dimensions  
then a batch of two bivariate normal distributions will be created.

In [24]:
# Define a multivariate Gaussian distribution with broadcasting
import tensorflow as tf
import tensorflow_probability as tfp
tf.keras.utils.set_random_seed(seed=42)

loc = [[0], [1]]
scale_diag = [1, 0.5]

batch_of_mvt_normals = tfp.distributions.MultivariateNormalDiag(
    loc=loc, scale_diag=scale_diag)

In [25]:
# Print the distribution - note the event_shape and batch_shape

batch_of_mvt_normals

<tfp.distributions.MultivariateNormalDiag 'MultivariateNormalDiag' batch_shape=[2] event_shape=[2] dtype=float32>

In [26]:
# Print the distribution parameters
# There is a batch of two distributions with different means and same covariance

batch_of_mvt_normals.parameters

{'loc': ListWrapper([ListWrapper([0]), ListWrapper([1])]),
 'scale_diag': ListWrapper([1, 0.5]),
 'validate_args': False,
 'allow_nan_stats': True,
 'experimental_use_kahan_sum': False,
 'name': 'MultivariateNormalDiag'}

Knowing that, for multivariate distributions, TensorFlow

- interprets the final axis of an array of parameters as the event shape,


- and broadcasts over the remaining axes,  

can you predict what the batch and event shapes will if we pass the arguments


    loc = [ [ 1.,  1.,  1.],
            [-1., -1., -1.] ] # shape (2, 3)
    scale_diag = [ [[0.1, 0.1, 0.1]],
                   [[10., 10., 10.]] ] # shape (2, 1, 3)
                   
to `MultivariateNormalDiag`?

Solution:

Align the parameter array shapes on their last axis, prepending 1s where necessary:  
    
           loc: 1 x 2 x 3  
    scale_diag: 2 x 1 x 3  

The final axis has size 3, so `event_shape = (3)`. The remaining axes are broadcast over to yield  
    
           loc: 2 x 2 x 3  
    scale_diag: 2 x 2 x 3  

so `batch_shape = (2, 2)`.

Let's see if this is correct!

In [27]:
# Define a multivariate Gaussian distribution with broadcasting
import tensorflow as tf
import tensorflow_probability as tfp
tf.keras.utils.set_random_seed(seed=42)

loc = [[1], [-1]] # shape (2, 1)
scale_diag = [[[0.1, 0.1, 0.1]], [[10, 10, 10]]] # shape (2, 1, 3)

another_batch_of_mvt_normals = tfp.distributions.MultivariateNormalDiag(
    loc=loc, scale_diag=scale_diag)

In [28]:
# Print the distribution and note batch and event shapes - bingo!

another_batch_of_mvt_normals

<tfp.distributions.MultivariateNormalDiag 'MultivariateNormalDiag' batch_shape=[2, 2] event_shape=[3] dtype=float32>

In [29]:
# Print the distribution parameters

another_batch_of_mvt_normals.parameters

{'loc': ListWrapper([ListWrapper([1]), ListWrapper([-1])]),
 'scale_diag': ListWrapper([ListWrapper([ListWrapper([0.1, 0.1, 0.1])]), ListWrapper([ListWrapper([10, 10, 10])])]),
 'validate_args': False,
 'allow_nan_stats': True,
 'experimental_use_kahan_sum': False,
 'name': 'MultivariateNormalDiag'}

As we did before lets also look at broadcasting when we have batches of multivariate distributions.

In [30]:
# Define a batch of Normal distributions with broadcasting
import tensorflow as tf
import tensorflow_probability as tfp
tf.keras.utils.set_random_seed(seed=42)

loc = [[0], [1], [0]]
scale = [1, 10, 100, 1, 10, 100]

another_batch_of_normals = tfp.distributions.Normal(
    loc=loc, scale=scale)
another_batch_of_normals

<tfp.distributions.Normal 'Normal' batch_shape=[3, 6] event_shape=[] dtype=float32>

And to refresh our memory of `Independent` we'll use it below to roll the rightmost batch shape into the event shape.

In [31]:
# Create a multivariate Independent distribution
import tensorflow as tf
import tensorflow_probability as tfp
tf.keras.utils.set_random_seed(seed=42)

another_batch_of_mvt_normals = tfp.distributions.Independent(
    distribution=another_batch_of_normals, reinterpreted_batch_ndims=1)
another_batch_of_mvt_normals

<tfp.distributions.Independent 'IndependentNormal' batch_shape=[3] event_shape=[6] dtype=float32>

Now, onto the broadcasting:

In [32]:
# Use broadcasting with the prob method
# B shaped input (broadcast over event)
import tensorflow as tf
tf.keras.utils.set_random_seed(seed=42)

sample = tf.random.uniform(shape=(3, 1), dtype=tf.float32)
another_batch_of_mvt_normals.prob(value=sample)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.5805955e-09, 2.9402489e-09, 3.5549474e-09], dtype=float32)>

In [33]:
# Use broadcasting with the prob method
# E shaped input (broadcast over batch)
import tensorflow as tf
tf.keras.utils.set_random_seed(seed=42)

sample = tf.random.uniform(shape=(1, 6), dtype=tf.float32)
another_batch_of_mvt_normals.prob(value=sample)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.8991622e-09, 3.2812235e-09, 2.8991622e-09], dtype=float32)>

In [34]:
# Use broadcasting with the prob method
# [S,B,E] shaped input (broadcast over samples)
import tensorflow as tf
tf.keras.utils.set_random_seed(seed=42)

sample = tf.random.uniform(shape=(2, 3, 6), dtype=tf.float32)
another_batch_of_mvt_normals.prob(value=sample)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2.8991622e-09, 2.8752789e-09, 2.6618117e-09],
       [2.8392129e-09, 2.7802218e-09, 2.2349427e-09]], dtype=float32)>

In [35]:
# [S,b,e] shaped input where [b,e] can be broadcast agaisnt [B,E]
import tensorflow as tf
tf.keras.utils.set_random_seed(seed=42)

sample = tf.random.uniform(shape=(2, 1, 6), dtype=tf.float32)
another_batch_of_mvt_normals.prob(value=sample)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2.8991622e-09, 3.2812235e-09, 2.8991622e-09],
       [2.9772862e-09, 2.8752789e-09, 2.9772862e-09]], dtype=float32)>

As a final example with `log_prob` instead of `prob`

In [36]:
# Use broadcasting with the log_prob method
# [S,b,e] shaped input where [b,e] can be broadcast agaisnt [B,E]
import tensorflow as tf
tf.keras.utils.set_random_seed(seed=42)

sample = tf.random.uniform(shape=(2, 3, 1), dtype=tf.float32)
another_batch_of_mvt_normals.log_prob(value=sample)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-19.775246, -19.644772, -19.454926],
       [-19.547066, -20.272385, -19.802654]], dtype=float32)>

You should now feel confident specifying batches of distributions using broadcasting. As you may have already guessed, broadcasting is especially useful when specifying grids of hyperparameters.

If you don't feel entirely comfortable with broadcasting quite yet, don't worry: re-read this notebook, go through the further reading provided below, and experiment with broadcasting in both numpy and TensorFlow, and you'll be broadcasting in no time.

### Further reading and resources
* Numpy documentation on broadcasting: https://numpy.org/devdocs/user/theory.broadcasting.html
* https://www.tensorflow.org/xla/broadcasting